### ISSUE TITLE
RingCentral chrome extension not functioning for a Canadian account

### ISSUE THREAD

**Issue by FilipinaW** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#5] opened 2019-03-26 14:59 UTC
I figure I will open a separate ticket, as my issues were piggy-backing on other tickets - and some of them are being closed.  This extension is not working for me at all.  I can sign in now, but nothing else is working.  Customer information is not displayed when call comes in.  Can't add calls from the log either as it's not finding a match (no related contact).  We would love for this extension to work, so I can install for all the users...

**Comment by FilipinaW** [comment] 2019-03-26 15:02
I can make calls and send SMS from the chrome extension - that's the only 2 items that work.

**Comment by FilipinaW** [comment] 2019-03-26 18:26
Also, session expires and goes into offline mode with no option to sign back in.

**Comment by zxdong262** [comment] 2019-03-26 23:45
Hi @FilipinaW Can you auth to access pipedrive contacts? And could you give some phone number format you use(not real number), I will try to reproduce this.

**Comment by FilipinaW** [comment] 2019-03-27 12:12
I authorized twice - once on sign in screen (it's the second screen after I enter my credentials), and then when I try to add manually to the log - it asked again the first time i do it.  The phone number format in Pipedrive is (012)345-6789.  the phone number format in the pop up RC app from the chrome extension is (012) 345-6789 - there is an extra space after second bracket.   When i try to add to the log manually, the little pop up "Sync call log to Pipedrive" formats it +10123456789 - it adds +1 and removes everything except digits.

**Comment by FilipinaW** [comment] 2019-04-04 12:21
Hi @zxdong262 - just wondering if you had any progress with troubleshooting here.

**Comment by zxdong262** [comment] 2019-04-05 07:14
@FilipinaW Sorry for the delay, next week I will check this.

**Comment by zxdong262** [comment] 2019-04-08 07:10
@FilipinaW  Released new version, now session timeout is 7 days, and support full contacts sync, can you try it, and let know how it works, thank you.

https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/releases/tag/v0.4.2

**Comment by FilipinaW** [comment] 2019-04-08 18:57
Unfortunately the extension is still not recognizing/matching any numbers to any contacts.

**Comment by zxdong262** [comment] 2019-04-09 01:30
@FilipinaW Can you post the screenshot of Chrome console log here when you try add call log, I would like to see if there is some error happens which I can not reproduce.

**Comment by FilipinaW** [comment] 2019-04-09 12:31
![image](https://user-images.githubusercontent.com/47257281/55800468-d0279400-5aa1-11e9-83a8-61457281107b.png)

**Comment by FilipinaW** [comment] 2019-04-09 12:32
You can see in the background that it's an existing number for one of our contacts. yet I get below error: 
![image](https://user-images.githubusercontent.com/47257281/55800537-f2b9ad00-5aa1-11e9-81d1-74116b2d5290.png)

**Comment by FilipinaW** [comment] 2019-04-09 12:35
![image](https://user-images.githubusercontent.com/47257281/55800726-6491f680-5aa2-11e9-98c9-248f21e475c5.png)

**Comment by FilipinaW** [comment] 2019-04-09 12:38
![image](https://user-images.githubusercontent.com/47257281/55800899-c9e5e780-5aa2-11e9-8edb-9d7d50ffdef7.png)

**Comment by FilipinaW** [comment] 2019-04-17 19:48
Any ideas on how to make this work for Canadian accounts?

**Comment by zxdong262** [comment] 2019-04-18 01:47
@FilipinaW Sorry, I can not access CA accont yet, it may take some time to test this.

**Comment by zxdong262** [comment] 2019-04-23 01:49
[pipedrive-embeddable-ringcentral-phone-0.4.8b1.zip](https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/files/3105454/pipedrive-embeddable-ringcentral-phone-0.4.8b1.zip)

Hi @FilipinaW 

I build a special version with detailed console log, which will show why it do not match, Can you try this one? and send me the log? you can send it to drake.zhao@ringcentral.com.

**Comment by FilipinaW** [comment] 2019-05-08 14:58
Hi, any progress with the info i sent you?

**Comment by zxdong262** [comment] 2019-05-09 01:02
@FilipinaW Sorry for the delay. Still need more test, maybe next week.

**Comment by FilipinaW** [comment] 2019-07-29 15:14
Hi, I installed the latest version and the extension seems to be working now.  We see one issue though:  Pipedrive contacts are not shared across all the users - I'm only able to log calls that are for contacts I'm the owner off.   Contacts owned by other reps do not show on my Pipedrive contact list.  Is this a standard behaviour?

**Comment by zxdong262** [comment] 2019-07-30 00:40
@FilipinaW 

It can only fetch the contacts data that your pipedrive account shows, since it uses the same api that your browser uses in pipedrive.com. If you can do it in your browser, it can be done in this extension.

Not sure what do you mean by "shared across all the users". Can you explain in more detail?

**Comment by FilipinaW** [comment] 2019-07-30 13:04
If i'm not the owner of the contact in Pipedrive, that contact is not showing listed in the extension - therefore I cannot log the call, nor it shows the right name in the call log of the extension.

**Comment by FilipinaW** [comment] 2019-07-30 13:04
![image](https://user-images.githubusercontent.com/47257281/62131344-01bea800-b2a9-11e9-8240-bac1ee8ee496.png)

![image](https://user-images.githubusercontent.com/47257281/62131359-07b48900-b2a9-11e9-94d1-ae1bcb184b67.png)

**Comment by FilipinaW** [comment] 2019-07-30 13:05
as soon as I change back the ownership to me, contact is found.  This behaviour makes the extension useless for logging as we have many people calling accounts/contacts or taking inbound calls.
![image](https://user-images.githubusercontent.com/47257281/62131452-3b8fae80-b2a9-11e9-9a62-e22b53b1b5b2.png)

**Comment by zxdong262** [comment] 2019-07-30 20:48
@FilipinaW I see, I will try to solve this problem, thank you for the feedback.

**Comment by zxdong262** [comment] 2019-07-31 00:10
Done, let me know if it works for you, thank you for the feedback!
https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/releases/tag/v0.7.0

@FilipinaW

**Comment by FilipinaW** [comment] 2019-07-31 14:06
Yes!  Now I can see all the contacts listed in the extension contact list.  Perfect.

**Comment by zxdong262** [comment] 2020-02-26 00:39
Close it now, feel free to submit another if needed, feedbacks are always welcome.

**Closed by zxdong262** 2020-02-26 00:39 UTC
