### ISSUE TITLE
History length and phone number formatting 

### ISSUE THREAD

**Issue by FilipinaW** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#17] opened 2019-08-14 13:39 UTC
Hi:  right now the history in extension only shows the last 6 calls - can that be extended to show a longer list?  2nd issue is that some of the numbers do not match with contacts - I believe it might be because of phone number formatting.  What is the extension expecting?  I see one that was entered into Pipedrive with xxx-xxx-xxxx format, and the extension is not picking it up as a match.

**Comment by FilipinaW** [comment] 2019-08-14 20:22
actually to add 3rd issues I see:  when call is added to pipedrive the length is logged in hours instead of minutes... so my 3 minute call shows as a 3 hour call...

**Comment by zxdong262** [comment] 2019-08-15 02:31
@FilipinaW 

- Can you give a screenshot about the call length.
- About the no match problem, can you check this article: https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/issues/137, xxx-xxx-xxxx format is OK.


@embbnux Do you know about the call history problem?

**Comment by embbnux** [comment] 2019-08-15 02:48
@FilipinaW @zxdong262 Now the widget only fetch recent 7 days calls from server. It is by design in our early production requirement. Need to talk with PM to support load older calls.

**Comment by FilipinaW** [comment] 2019-08-15 12:34
number formatting:  I have authorized and installed extension as it works for numbers when its only digits or (xxx) xxx-xxxx format.  As soon as I change the number to xxx-xxx-xxxx format, it is no longer matching to the contact/log.

![image](https://user-images.githubusercontent.com/47257281/63094732-3a13e680-bf37-11e9-9b5c-497031ec111d.png)


![image](https://user-images.githubusercontent.com/47257281/63094842-7ba49180-bf37-11e9-92c5-615796f4ebad.png)

**Comment by FilipinaW** [comment] 2019-08-15 12:35
number formatting: I have authorized and installed extension as it works for numbers when its only digits or (xxx) xxx-xxxx format. As soon as I change the number to xxx-xxx-xxxx format, it is no longer matching to the contact/log.

![image](https://user-images.githubusercontent.com/47257281/63094887-a1319b00-bf37-11e9-9b64-935d62527a91.png)

![image](https://user-images.githubusercontent.com/47257281/63094889-a55db880-bf37-11e9-8c70-4dd0f6bce20f.png)

**Comment by FilipinaW** [comment] 2019-08-15 12:36
number formatting: I have authorized and installed extension as it works for numbers when its only digits or (xxx) xxx-xxxx format. As soon as I change the number to xxx-xxx-xxxx format, it is no longer matching to the contact/log.

![image](https://user-images.githubusercontent.com/47257281/63094918-c2928700-bf37-11e9-8dd1-b469dba1c49e.png)

![image](https://user-images.githubusercontent.com/47257281/63094932-ca522b80-bf37-11e9-8b81-7d3b6aea8860.png)

**Comment by FilipinaW** [comment] 2019-08-15 12:38
call log length:  it's not 7 days, there is no scrolling on the screen so it's just whatever fits on one page:
![image](https://user-images.githubusercontent.com/47257281/63094989-04bbc880-bf38-11e9-9a5b-25dd54e9b713.png)

**Comment by FilipinaW** [comment] 2019-08-15 12:43
Call length wrong:  below call was 3 minutes long ... not 3 hours:

![image](https://user-images.githubusercontent.com/47257281/63095221-bbb84400-bf38-11e9-99f6-263561b031c8.png)

**Comment by embbnux** [comment] 2019-08-15 16:42
Hi @FilipinaW It is definitely a bug. will fix it soon.
Thanks so much for feedback this.

> call log length: it's not 7 days, there is no scrolling on the screen so it's just whatever fits on one page:
> ![image](https://user-images.githubusercontent.com/47257281/63094989-04bbc880-bf38-11e9-9a5b-25dd54e9b713.png)

**Comment by zxdong262** [comment] 2019-08-16 06:05
@FilipinaW Should fixed now,  you may refresh to check it

**Comment by FilipinaW** [comment] 2019-08-16 12:43
Yes, thanks.  It's back to 7 days of history now.

**Comment by FilipinaW** [comment] 2019-09-04 12:48
Could you please provide the status for the 2 outstanding issues:  number formatting and call length that ends up in the calendar?

**Comment by zxdong262** [comment] 2019-09-05 01:07
@FilipinaW Sorry for the delay, I checked, the time format is right, the 3:37 in your screenshot means 3 minutes 37 sec, not 3 hour 37 minutes, please confirm this.

**Comment by zxdong262** [comment] 2019-09-05 02:07
@FilipinaW As I tested it, all formats works, can you provide some numbers that could not match and some numbers that could match? You can send to my email drake.zhao@ringcentral.com(I would not call these numbers.)

**Comment by FilipinaW** [comment] 2019-09-05 20:13
@zxdong262 for the call length.. 3 minutes should be 00:03.  If you even look at available durations in the pipedrive field dropdown - they are in 15 minute intervals:  
![image](https://user-images.githubusercontent.com/47257281/64377269-1274e300-cff8-11e9-9fec-c572f52676b7.png)
 I'll send you email with examples for number formatting.

**Comment by zxdong262** [comment] 2019-09-05 22:38
@FilipinaW I believe it is seconds, think about it, providing a eight hour duration option for phone call is not common.

**Comment by FilipinaW** [comment] 2019-10-02 17:51
that's exactly what I'm saying.  Open up the calendar to see past calls - they all show to be hours long instead of minutes long.  I can send you plenty examples/screenshots directly to your email if it helps.

**Comment by zxdong262** [comment] 2019-10-08 00:29
@FilipinaW Let check again about this.

**Comment by zxdong262** [comment] 2019-10-17 00:46
@FilipinaW I thought I could find the problem, but failed, could you send the screenshot you mentioned? Thank you.

**Comment by zxdong262** [comment] 2020-02-26 00:38
Close it now, feel free to submit another if needed, feedbacks are always welcome.

**Closed by zxdong262** 2020-02-26 00:38 UTC
