### ISSUE TITLE
Call logging not functioning

### ISSUE THREAD

**Issue by jtterror** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#2] opened 2019-02-12 22:02 UTC
auto log issues with U.S. pipedrive. does not log after call or when clicking or double clicking log call from the call log. if error message shows it says no contact info.

**Comment by zxdong262** [comment] 2019-02-13 07:11
Hi @jtterror 

What is your phone number, can you give one example, I would like investigate this.

**Comment by jtterror** [comment] 2019-02-13 12:53
Hello Zhao,

 

                The number is typically in this format 9995556666 or 19995556666. Pipe drive auto formats the number to 999-555-6666 the other 1(999) 555-6666 but there are also numbers with 999.555.6666 or 999- 555 -6666.

**Comment by zxdong262** [comment] 2019-02-20 01:01
Hi @jtterror I released new version 0.3.8, can you test about this issue?

**Comment by jtterror** [comment] 2019-02-20 13:39
It seems to be more reliable as in each call it is trying to log the information but still it is not finding the contact on pipedrive.

 

 



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by zxdong262** [comment] 2019-02-21 02:12
@jtterror Hi,

Released new version about this issue:
https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/releases/tag/v0.3.9

Can you try it?

**Comment by jtterror** [comment] 2019-02-21 17:38
The new rev has errors under the Chrome pipedrive extension. Chrome is up to
date.

 

 



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by jtterror** [comment] 2019-02-22 18:25
The chrome extension is still coming up with errors

 



 

 

 



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by jtterror** [comment] 2019-02-22 18:37
Error is

 

Uncaught ()

 

 

 



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by jtterror** [comment] 2019-02-22 18:37
Again chrome is up to date and running v3.10

 

Error is

 

Uncaught (in promise) TypeError: A phone number must either be a string or
an object of a shape {phone, [country]}

 

Stacktrace

Content.js:1

!function(e){var t={};function n(a)}..

 

 

 



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by jtterror** [comment] 2019-02-22 19:06
Uncaught (in promise) error: Extension context invalidated

 

 

 



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by zxdong262** [comment] 2019-02-24 23:34
@jtterror So the old version works, new version does not?

**Comment by zxdong262** [comment] 2019-02-25 01:05
> Again chrome is up to date and running v3.10 Error is Uncaught (in promise) TypeError: A phone number must either be a string or an object of a shape {phone, [country]} Stacktrace Content.js:1 !function(e){var t={};function n(a)}..
> […](#)
> --- This email has been checked for viruses by Avast antivirus software. https://www.avast.com/antivirus

Can you send me screenshot of your page when this error happens, you can cover the credential parts, I think the error happens due to phone number related problem, but I can not reproduce in my test env.

**Comment by jtterror** [comment] 2019-02-25 15:27
i sent you an email with a screenshot of pipedrive and a log file from chromes devtools

**Comment by jtterror** [comment] 2019-02-26 13:25
Right in a normal working condition it is suppose to say call logged in a popup on the left. However, instead of success it always says contact not found in its place. It simply has never logged a call even using the manual log link. Not sure if it helps but ring central does add a 1 in front of the call.

**Comment by FilipinaW** [comment] 2019-02-26 17:26
I think I have similar issue - I get 'no related contact' when trying to manually log a call, and anything automatic is not working.

**Comment by zxdong262** [comment] 2019-03-01 02:42
Hi @FilipinaW All your phone numbers are just US numbers, right?

**Comment by FilipinaW** [comment] 2019-03-07 13:49
nope... we have Canadian account with all Canadian numbers.

**Comment by GiffordChester** [comment] 2019-03-18 18:27
Hello @zxdong262 do we have any updates regarding the reported issue wherein the call logging feature is not working?

We've ensured that the phone numbers are correct and without duplicates but we're still getting a "No contact related" pop-up on the left side. We also tried using different phone number formats e.g. 0123456789, +44234567890 but to no avail. However, using a US account works fine upon testing.

**Comment by FilipinaW** [comment] 2019-03-18 19:16
We also had no luck with the Canadian account.  On top of it it almost looks like the sign on times out and I'm not able to sign back in.

**Comment by zxdong262** [comment] 2019-03-19 01:07
@FilipinaW @GiffordChester I am going to get a CA account to test more.

**Comment by zxdong262** [comment] 2019-03-19 02:22
@FilipinaW @GiffordChester https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/releases/tag/v0.3.13 Can you try this, should fix now.

**Comment by FilipinaW** [comment] 2019-03-19 12:22
I'm trying to add a call from yesterday by clicking on "log to pipedrive" - and nothing happens.

**Comment by zxdong262** [comment] 2019-03-20 07:32
@FilipinaW Do the call you clicked has a contact name or just phone number?

**Comment by FilipinaW** [comment] 2019-03-20 12:10
I just tried different entries from the log - it's inconsistent.  sometimes prompt appears, sometimes nothing happens.  In cases where prompt appears, it's still not matching the call against any contacts.

**Comment by DylanM72** [comment] 2019-03-25 14:28
@GiffordChester @zxdong262 UK Account of RingCentral & Pipedrive - Logging issues are still happening, and calls are not being logged or matched to any contact.

**Comment by zxdong262** [comment] 2019-03-26 01:36
@DylanM72 Are you using the lastest release?

**Comment by DylanM72** [comment] 2019-04-01 18:37
Hello @zxdong262 we've tried using version 0.3.14 but we're still not getting the calls logged and it's not matching to a record as well.

We've noticed that the version on the integrated pop-up shows version 0.2.0. Should this be the correct version? Please do note that we're using a RingCentral UK account and the phone numbers are in +44xxxx or 0xxxxx format.

**Comment by karaghl** [comment] 2019-06-25 09:49
Having same issue but it works if i change the number in the contact to +447799.....

But otherwise its saying no contact related.

also, does it logg missed calls?

**Comment by zxdong262** [comment] 2019-07-25 06:58
@karaghl Sorry missed the message, I would do more test about this next week.

**Comment by zxdong262** [comment] 2020-02-26 00:40
Close it now, feel free to submit another if needed, feedbacks are always welcome.

**Closed by zxdong262** 2020-02-26 00:40 UTC
Labels: need investigate
